version: "3"

services:
  server1:
    build:
      dockerfile: Dockerfile.dev
      context: ./demo-server-1
    volumes:
      - /usr/src/app/node_modules
      - ./demo-server-1:/usr/src/app

  server2:
    build:
      dockerfile: Dockerfile.dev
      context: ./demo-server-2
    volumes:
      - /usr/src/app/node_modules
      - ./demo-server-2:/usr/src/app

  nginx:
    # 재시작 정책
    # 죽었을 때 항상 재시작
    restart: always
    build: ./demo-nginx
    ports:
      - "3000:80"
