on:
  push:
    branches:
      - master

name: Deploy to Amazon Beanstalk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Generate deployment package
      run: zip -r deploy.zip .
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: demo-app
        environment_name: DemoApp-env
        version_label: ${{ github.run_number }}
        version_description: ${{ github.sha }}
        region: ap-northeast-2
        deployment_package: deploy.zip
